# Generated by Django 4.2.9 on 2025-08-31 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name (e.g., Gmail, Outlook)', max_length=100)),
                ('smtp_host', models.CharField(help_text='SMTP server hostname', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP port number')),
                ('username', models.CharField(help_text='Email username/address', max_length=255)),
                ('password', models.CharField(help_text='Email password or app password', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('from_email', models.CharField(help_text='From email address', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Is this configuration active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom SMTP Configuration',
                'verbose_name_plural': 'Custom SMTP Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='Recipient email address', max_length=255)),
                ('subject', models.CharField(help_text='Email subject', max_length=255)),
                ('message', models.TextField(help_text='Email message content')),
                ('status', models.CharField(choices=[('sent', 'Sent Successfully'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
                ('smtp_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='crm.customsmtpconfig')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
