# Generated by Django 4.2.9 on 2025-09-01 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_progress'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Payment description', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_type', models.CharField(choices=[('advance', 'Advance Payment'), ('milestone', 'Milestone Payment'), ('final', 'Final Payment'), ('installment', 'Regular Installment')], default='installment', max_length=20)),
                ('due_date', models.DateField(help_text='When this payment is due')),
                ('paid_date', models.DateField(blank=True, help_text='When this payment was actually paid', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_installments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Payment Installment',
                'verbose_name_plural': 'Payment Installments',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
